sudo: required
dist: trusty

language: node_js
node_js:
  - "8"

cache: yarn

addons:
  chrome: stable
  firefox: "54.0"

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s --"
  - export PATH="$HOME/.yarn/bin:$PATH"

