sudo: required
dist: trusty

language: node_js
node_js:
  - "8"

cache: yarn

addons:
  firefox: "54.0"

before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s --"
  - export PATH="$HOME/.yarn/bin:$PATH"

