sudo: required
dist: trusty

language: node_js
node_js:
  - "8"

env:
  - MOZ_HEADLESS=1

cache: yarn

addons:
  chrome: stable
  firefox: latest

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s --"
  - export PATH="$HOME/.yarn/bin:$PATH"

